[package]
authors = ["Zack Smith <zack.t.smith37@gmail.com>"]
edition = "2018"
name = "shitpost-bot"
version = "0.1.0"

[dependencies]
rand = "0.7"
serde_json = "1.0"
regex = "1.3.9"
lazy_static = "1.4.0"
serenity = { default-features=false, features=["builder", "cache", "http", "model", "utils", "default_native_tls"], git="https://github.com/serenity-rs/serenity", branch="current" }
